apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-chart.fullname" . }}-secret
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
