apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask
    day: "6"
spec:
  containers:
  - name: flask
    image: ashytcloud/myapp:latest
    ports:
      - containerPort: 5000
    env:
      - name: APP_VERSION
        value: "day6-k8s"
